---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04
    driver:
      box: boxesio/trusty64-chef

suites:
  - name: default
    data_bags_path: test/integration/default/data_bags
    run_list:
      - recipe[dokku::default]
      - recipe[dokku::ssh_keys]
      - recipe[dokku::plugins]
      - recipe[dokku::apps]
      - recipe[dokku::certificates]
    attributes:
      dokku:
        domain: dokku.me
        ssh_keys:
          - user: test
            key: public_key
        plugins:
          - name: redis
            url: https://github.com/dokku/dokku-redis.git
            committish: 659cd084
        apps:
          - name: demo-app
          - name: app-for-destroying
            action: create
          - name: app-for-destroying
            action: destroy
